import { createCLI, defineCommand, option } from "@bunli/core";
import { z } from "zod";
import { encrypt, generateRandomSalt, hashPassword } from "..";
import { description, version } from "../../package.json";

import _wrapper from "../../dist/wrapper/index.html";
const wrapperHtml = _wrapper as unknown as string;

import { readdir, rm } from "node:fs/promises";
import { join } from "node:path";
import { loadConfig } from "./config";
import { fileIsEntryPoint, filterIgnoredFiles } from "./files";

const cli = await createCLI({
  name: "swcrypts",
  version,
  description,
});

const buildCommand = defineCommand({
  name: "build" as const,
  description: "Build and encrypt assets for deployment",
  options: {
    indir: option(z.string(), { short: "i" }),
    outdir: option(z.string(), { short: "o" }),

    salt: option(z.string().optional(), { short: "s" }),
  },
  handler: async ({ flags, prompt }) => {
    const config = await loadConfig(flags.indir);

    const files = filterIgnoredFiles(
      await readdir(flags.indir, { recursive: true }),
    );

    if (files.length === 0) {
      console.error("No files found in the input directory.");
      process.exitCode = 1;
      return;
    }

    console.log(`Found ${files.length} files to encrypt.`);

    const password = await prompt.password("Enter password:");
    let salt =
      config.salt ||
      (await prompt.password("Enter salt (or leave empty for random):"));

    if (!salt) {
      salt = generateRandomSalt();

      console.log("Using random salt:", salt);

      await Bun.write(
        ".swcrypts.jsonc",
        `\
{
  // This file was generated by SwCrypts to store the salt used for encryption.
  "salt": ${JSON.stringify(salt)}
}
`,
      );
    } else if (!/^[0-9a-fA-F]{32}$/.test(salt)) {
      console.error("Salt must be 32 hex characters (16 bytes in hex)");
      process.exitCode = 1;
      return;
    }

    const passwordHash = await hashPassword(password, salt);

    await rm(flags.outdir, { recursive: true, force: true });

    for (const relativeFilePath of files) {
      const filePath = join(flags.indir, relativeFilePath);
      const file = Bun.file(filePath);
      const data = await file.bytes();

      const isEntryPoint = fileIsEntryPoint(relativeFilePath);

      const encryptedData = await encrypt(data, passwordHash);
      const outputFilePath = join(
        flags.outdir,
        relativeFilePath + (isEntryPoint ? "" : ".enc"),
      );

      let dataToWrite: Uint8Array | string;

      if (isEntryPoint) {
        dataToWrite = wrapperHtml
          .replace(
            '"{{ENCRYPTED_PAGE}}"',
            JSON.stringify(encryptedData.toBase64()),
          )
          .replace('"{{SALT}}"', JSON.stringify(salt));
      } else {
        dataToWrite = encryptedData;
      }

      await Bun.write(outputFilePath, dataToWrite);
    }
  },
});

cli.command(buildCommand);

await cli.run();
