import type { FileMetadata } from "@swcrypts/core/metadata";

import { readdir, rm } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

import { defineCommand, option } from "@bunli/core";
import { z } from "zod";

import { serviceWorkerFileName } from "@swcrypts/core/constants";
import {
  deriveFilePathsKey,
  encrypt,
  encryptFilePath,
  hashPassword,
} from "@swcrypts/core/crypto";
import { generateRandomSalt, isValidSalt } from "@swcrypts/core/crypto/salt";
import { fileIsEntryPoint, filterIgnoredFiles } from "@swcrypts/core/files";
import {
  generateCryptoCheck,
  getServiceWorkerJs,
  getWrapperHtml,
} from "@swcrypts/core/wrapper";
import { loadConfig } from "../config";

export default defineCommand({
  name: "build" as const,
  description: "Build and encrypt assets for deployment",
  options: {
    indir: option(z.string(), {
      short: "i",
      description: "Input directory containing static site to encrypt.",
    }),
    outdir: option(z.string(), {
      short: "o",
      description: "Output directory for encrypted site.",
    }),

    config: option(z.string().optional(), {
      short: "c",
      description:
        "Path to config file. If not provided, the CLI will look for a config file in the input directory and CWD.",
    }),
    password: option(z.string().optional(), {
      short: "p",
      description:
        "Password for encryption. Be careful with this option as it may expose your password in command history.",
    }),
    salt: option(z.string().optional(), { short: "s" }),
  },
  handler: async ({ flags, prompt }) => {
    const [config, configPath] = await loadConfig(flags.config, flags.indir);

    const files = filterIgnoredFiles(
      (await readdir(flags.indir, { recursive: true, withFileTypes: true }))
        .filter((entry) => entry.isFile())
        .map((entry) =>
          relative(flags.indir, join(entry.parentPath, entry.name)),
        ),
    );

    if (files.length === 0) {
      console.error("No files found in the input directory.");
      process.exitCode = 1;
      return;
    }

    console.debug(`Found ${files.length} files to encrypt.`);

    const password =
      flags.password ||
      config.password ||
      process.env.SWCRYPTS_PASSWORD ||
      (await prompt.password("Enter password:"));

    if (!password) {
      console.error("Password is required for encryption.");
      process.exitCode = 1;
      return;
    }

    let salt =
      flags.salt ||
      config.salt ||
      process.env.SWCRYPTS_SALT ||
      (await prompt.password("Enter salt (or leave empty for random):"));

    if (!salt) {
      salt = generateRandomSalt();

      console.log("Using random salt:", salt);

      await Bun.write(
        join(flags.indir, ".swcrypts.jsonc"),
        `\
{
  // This file was generated by SwCrypts to store the salt used for encryption.
  "$schema": "https://raw.githubusercontent.com/lafkpages/swcrypts/main/packages/cli/config.schema.json",
  "salt": ${JSON.stringify(salt)}
}
`,
      );
    } else if (!isValidSalt(salt)) {
      console.error("Salt must be 32 hex characters (16 bytes in hex)");
      process.exitCode = 1;
      return;
    }

    const hashedPassword = await hashPassword(password, salt);
    const cryptoCheck = await generateCryptoCheck(hashedPassword);
    const filePathsKey = await deriveFilePathsKey(hashedPassword);

    const customStylesPath =
      config.customStyles && configPath
        ? resolve(configPath, "..", config.customStyles)
        : null;
    const customStyles = customStylesPath
      ? await Bun.file(customStylesPath).text()
      : null;

    await rm(flags.outdir, { recursive: true, force: true });

    const wrapperHtml = getWrapperHtml({
      ...config, // careful if new fields are added
      cryptoCheck,
      salt,
      customStyles,
    });

    const encoder = new TextEncoder();

    for (const relativeFilePath of files) {
      if (relativeFilePath === serviceWorkerFileName) {
        console.warn(
          `Skipping ${relativeFilePath} because it is internally reserved`,
        );
        continue;
      }

      const filePath = join(flags.indir, relativeFilePath);
      const file = Bun.file(filePath);

      const data = await file.bytes();
      const metadata = encoder.encode(
        JSON.stringify({ mimeType: file.type } satisfies FileMetadata),
      );

      const payload = new DataView(
        new ArrayBuffer(6 + metadata.length + data.length),
      );
      payload.setUint8(0, 1);
      payload.setUint8(1, 0);
      payload.setUint32(2, metadata.length);
      const payloadBytes = new Uint8Array(payload.buffer);
      payloadBytes.set(metadata, 6);
      payloadBytes.set(data, 6 + metadata.length);

      const isEntryPoint = fileIsEntryPoint(relativeFilePath);

      const encryptedData = await encrypt(payload.buffer, hashedPassword);
      const encryptedPath = await encryptFilePath(
        relativeFilePath,
        filePathsKey,
      );

      const outputFilePath = join(flags.outdir, relativeFilePath);
      const outputFilePathEnc =
        join(flags.outdir, encryptedPath) + ".swcrypts.enc";

      if (isEntryPoint) {
        await Bun.write(outputFilePath, wrapperHtml);
      }

      await Bun.write(outputFilePathEnc, encryptedData);
    }

    await Bun.write(
      join(flags.outdir, serviceWorkerFileName),
      getServiceWorkerJs(),
    );
  },
});
